module StackProcessing

// open StackCore

// //////////////////// StackCore
type Stage<'S,'T> = SlimPipeline.Stage<'S,'T>
type Profile = SlimPipeline.Profile
type ProfileTransition = SlimPipeline.ProfileTransition
type ResourceOps<'T> = SlimPipeline.ResourceOps<'T>
type StageTimeCoefficients = SlimPipeline.StageTimeCoefficients
type Window<'T> = SlimPipeline.Window<'T>
type ChunkIndex = StackCore.ChunkIndex
type ChunkLayout = StackCore.ChunkLayout
type Chunk<'T when 'T: equality> = StackCore.Chunk<'T>
type VectorChunk<'T when 'T: equality> = StackCore.VectorChunk<'T>
module Chunk = StackCore.Chunk
//type Slice<'S when 'S: equality> = Slice.Slice<'S>
type Image<'S when 'S: equality> = Image.Image<'S>
type ImageFacts = Image.ImageFacts
type Point2D = StackCore.Point2D
type Polygon2D = StackCore.Polygon2D

let optimizerEnabled = StackCore.optimizerEnabled
let source = StackCore.source
let sourceWithOptimizer = StackCore.sourceWithOptimizer
let debug = StackCore.debug
let debugDefault = StackCore.debugDefault
let commandLineSource = StackCore.commandLineSource
let zip = StackCore.zip
let (>=>) = StackCore.(>=>)
let (-->) = StackCore.(-->)
let (>=>>) = StackCore.(>=>>)
let (>>=>) = StackCore.(>>=>)
let (>>=>>) = StackCore.(>>=>>)
let teeFst = StackCore.teeFst
let teeSnd = StackCore.teeSnd
let fork = StackCore.fork
let (-->>) = StackCore.(-->>)
let ignoreSingles = StackCore.ignoreSingles
let ignorePairs = StackCore.ignorePairs
let zeroMaker = StackCore.zeroMaker
let sink = StackCore.sink
let sinkList = StackCore.sinkList
let drain = StackCore.drain
let drainList = StackCore.drainList
let drainLast = StackCore.drainLast
let tap = StackCore.tap
let tapIt = StackCore.tapIt
let showChartData = StackCharts.showChartData
let showChartDataWithLabels = StackCharts.showChartDataWithLabels
let showChart = StackCharts.showChart
let showChartWithLabels = StackCharts.showChartWithLabels
let showChartXY = StackCharts.showChartXY
let showChartXYWithLabels = StackCharts.showChartXYWithLabels
let showImage = StackCharts.showImage
let showImageWithLabels = StackCharts.showImageWithLabels
let showChunk<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> (chunk: StackCore.Chunk<'T>) =
    StackCharts.showChunk<'T> chunk
let showChunkWithLabels<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> colorMap title xAxis yAxis (chunk: StackCore.Chunk<'T>) =
    StackCharts.showChunkWithLabels<'T> colorMap title xAxis yAxis chunk

// //////////////////// StackIO
type FileInfo = ImageFunctions.FileInfo
type ChunkInfo = StackIO.ChunkInfo
type Position3D<'T> = StackPoints.Position3D<'T>
type CoordinatePoint = StackPoints.CoordinatePoint
type PointSet = StackPoints.PointSet
type VectorizedMatrix = StackPoints.VectorizedMatrix
type Affine = TinyLinAlg.Affine
type AffineRegistrationOptions = StackRegistration.AffineRegistrationOptions
type AffineRegistrationResult = StackRegistration.AffineRegistrationResult
type RansacResult<'Model, 'Item> = StackRansac.RansacResult<'Model, 'Item>
type PointMatch2D = StackRansac.PointMatch2D
type ImageSetCoordinateSystem = StackManifest.ImageSetCoordinateSystem
type ImageSetTransform = StackManifest.ImageSetTransform
type ImageSetGrid = StackManifest.ImageSetGrid
type ImageSetItem = StackManifest.ImageSetItem
type ImageSetMember = StackManifest.ImageSetItem
type ImageSetManifest = StackManifest.ImageSetManifest
type StitchPlanItem = StackStitching.StitchPlanItem
type StitchPlan = StackStitching.StitchPlan
type ObjectConnectivity = StackObjects.ObjectConnectivity
type ObjectBounds = StackObjects.ObjectBounds
type StreamedObject = StackObjects.StreamedObject
type ObjectMeasurements = StackObjects.ObjectMeasurements
type ObjectSizeStats = StackObjects.ObjectSizeStats
type BiasPolynomialTerm = StackBias.BiasPolynomialTerm
type BiasPolynomialModel = StackBias.BiasPolynomialModel
type SerialSliceTransform = StackSerialSections.SerialSliceTransform
type SerialSliceManifest = StackSerialSections.SerialSliceManifest
type SerialVolumeGeometry = StackSerialSections.SerialVolumeGeometry
type Point3D = StackMesh.Point3D
type Triangle = StackMesh.Triangle
type TriangleSet = StackMesh.TriangleSet

let getStackDepth = StackIO.getStackDepth
let getFileInfo = ImageFunctions.getFileInfo
let getStackInfo = StackIO.getStackInfo
let volumeFilePath = StackIO.volumeFilePath
let getStackSize = StackIO.getStackSize
let getStackWidth = StackIO.getStackWidth
let getStackHeight = StackIO.getStackHeight
let getFilenames = StackIO.getFilenames
let readFiles<'T when 'T: equality> = StackIO.readFiles<'T>
let readFilesWithShape<'T when 'T: equality> = StackIO.readFilesWithShape<'T>
let readFilePairs<'T when 'T: equality> = StackIO.readFilePairs<'T>
let readFiltered<'T when 'T: equality> = StackIO.readFiltered<'T>
let read<'T when 'T: equality> = StackIO.read<'T>
let readVolume<'T when 'T: equality> = StackIO.readVolume<'T>
let readChunkVolume<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = StackIO.readChunkVolume<'T>
let readVolumeRandom<'T when 'T: equality> = StackIO.readVolumeRandom<'T>
let readVolumeRange<'T when 'T: equality> = StackIO.readVolumeRange<'T>
let readRandom<'T when 'T: equality> = StackIO.readRandom<'T>
let readRange<'T when 'T: equality> = StackIO.readRange<'T>
let getChunkInfo = StackIO.getChunkInfo
let getZarrInfo = StackIO.getZarrInfo
let getNexusInfo = StackIO.getNexusInfo
let getChunkFilename = StackIO.getChunkFilename
let readChunkSlices<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = StackIO.readChunkSlices<'T>
let readChunkSlicesRandom<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = StackIO.readChunkSlicesRandom<'T>
let readChunkSlicesRange<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = StackIO.readChunkSlicesRange<'T>
let chunkZero<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = ChunkFunctions.chunkZero<'T>
let chunkCoordinateX<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = ChunkFunctions.chunkCoordinateX<'T>
let chunkCoordinateY<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = ChunkFunctions.chunkCoordinateY<'T>
let chunkCoordinateZ<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = ChunkFunctions.chunkCoordinateZ<'T>
let chunkPolygonMask = ChunkFunctions.chunkPolygonMask
let chunkEuler2DTransformPath = ChunkFunctions.euler2DTransformPath
let chunkCreateByEuler2DTransformFromChunk<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = ChunkFunctions.createByEuler2DTransformFromChunk<'T>
let chunkRepeat<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = ChunkFunctions.chunkRepeat<'T>
let chunkRepeatStage<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = ChunkFunctions.chunkRepeatStage<'T>
let chunkPad<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = ChunkFunctions.pad<'T>
let chunkCrop<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = ChunkFunctions.crop<'T>
let chunkSqueeze<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = ChunkFunctions.squeeze<'T>
let chunkConcatenateAlong<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = ChunkFunctions.concatenateAlong<'T>
let chunkPermuteAxes<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = ChunkFunctions.permuteAxes<'T>
let chunkResample2DNative<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = ChunkFunctions.resample2DNative<'T>
let chunkEuler2DTransformNative<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = ChunkFunctions.euler2DTransformNative<'T>
let chunkEuler2DRotateNative<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = ChunkFunctions.euler2DRotateNative<'T>
let chunkResize<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = ChunkFunctions.chunkResize<'T>
let chunkResample<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = ChunkFunctions.chunkResample<'T>
let chunkShow<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = ChunkFunctions.show<'T>
let chunkSignedDistanceBandNativeParallelCollect = ChunkFunctions.signedDistanceBandNativeParallelCollect
let chunkVectorDotFloat32 = ChunkFunctions.vectorDotFloat32
let chunkVectorMagnitudeFloat32 = ChunkFunctions.vectorMagnitudeFloat32
let chunkVector3ToColorFloat32 = ChunkFunctions.vector3ToColorFloat32
let chunkVectorAngleToFloat32 = ChunkFunctions.vectorAngleToFloat32
let chunkConvolveVectorComponentsFloat32NativeParallelCollect = ChunkFunctions.convolveVectorComponentsFloat32NativeParallelCollect
let chunkToVectorImage<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = ChunkFunctions.toVectorImage<'T>
let chunkVectorElement<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> (componentId: uint) = ChunkFunctions.vectorElement<'T> componentId
let chunkVectorRange<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> (firstComponent: uint) (componentCount: uint) = ChunkFunctions.vectorRange<'T> firstComponent componentCount
let chunkAppendVectorElement<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = ChunkFunctions.appendVectorElement<'T>
let chunkVectorMapElements = ChunkFunctions.vectorMapElements
let chunkVector3ToColor = ChunkFunctions.vector3ToColor
let chunkColorToVector3 = ChunkFunctions.colorToVector3
let chunkVectorDot = ChunkFunctions.vectorDot
let chunkVectorMagnitude = ChunkFunctions.vectorMagnitude
let chunkVectorCross3D = ChunkFunctions.vectorCross3D
let chunkVectorAngleTo = ChunkFunctions.vectorAngleTo
let chunkPCA = ChunkFunctions.PCA
let chunkPCAFloat32 = ChunkFunctions.PCAFloat32
let chunkStructureTensorNativeParallelCollect = ChunkFunctions.structureTensorNativeParallelCollect
let chunkSelectGroupedVectorOutput = ChunkFunctions.selectGroupedVectorOutput
let chunkToComplex64 = ChunkFunctions.toComplex64
let chunkPolarToComplex64 = ChunkFunctions.polarToComplex64
let chunkComplex64Real = ChunkFunctions.complex64Real
let chunkComplex64Imag = ChunkFunctions.complex64Imag
let chunkComplex64Modulus = ChunkFunctions.complex64Modulus
let chunkComplex64Argument = ChunkFunctions.complex64Argument
let chunkComplex64Conjugate = ChunkFunctions.complex64Conjugate
let chunkFftXYFloat32ToComplex64Interleaved = ChunkFunctions.fftXYFloat32ToComplex64Interleaved
let chunkFftXYFloat32ToComplex64InterleavedParallelCollect = ChunkFunctions.fftXYFloat32ToComplex64InterleavedParallelCollect
let chunkInvFftXYComplex64InterleavedToFloat32 = ChunkFunctions.invFftXYComplex64InterleavedToFloat32
let chunkInvFftXYComplex64InterleavedToFloat32ParallelCollect = ChunkFunctions.invFftXYComplex64InterleavedToFloat32ParallelCollect
let chunkFftShift3DComplex64Interleaved = ChunkFunctions.fftShift3DComplex64Interleaved
let chunkConnectedComponentsSauf3DUInt8UInt32 = ChunkFunctions.connectedComponentsSauf3DUInt8UInt32
let chunkConnectedComponentsSauf3DUInt8UInt32ParallelCollect = ChunkFunctions.connectedComponentsSauf3DUInt8UInt32ParallelCollect
let chunkConnectedComponentsSauf3DUInt8 = ChunkFunctions.connectedComponentsSauf3DUInt8
let chunkHistogram<'T when 'T: equality and 'T: comparison and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = ChunkFunctions.histogramReducer<'T>
let chunkHistogramDense<'T when 'T: equality and 'T: comparison and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = ChunkFunctions.histogramDenseReducer<'T>
let chunkHistogramLeftEdges<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = ChunkFunctions.histogramLeftEdgesReducer<'T>
let chunkHistogramFixedBins<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = ChunkFunctions.histogramFixedBinsReducer<'T>
let chunkComputeStats<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = ChunkFunctions.computeStats<'T>
let chunkHistogramEqualizationDense<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = ChunkFunctions.histogramEqualizationDense<'T>
let chunkHistogramEqualizationLeftEdges<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = ChunkFunctions.histogramEqualizationLeftEdges<'T>
let chunkHistogramEqualizationSparse<'T when 'T: equality and 'T: comparison and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = ChunkFunctions.histogramEqualizationSparse<'T>
let chunkHistogramEqualization<'T when 'T: equality and 'T: comparison and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = ChunkFunctions.histogramEqualization<'T>
let chunkQuantiles = ChunkFunctions.quantiles
let chunkVolume = ChunkFunctions.volume
let chunkSumProjection<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = ChunkFunctions.chunkSumProjection<'T>
let chunkThresholdRange<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = ChunkFunctions.thresholdRange<'T>
let chunkClamp<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = ChunkFunctions.clamp<'T>
let chunkShiftScale<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = ChunkFunctions.shiftScale<'T>
let chunkIntensityWindow<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = ChunkFunctions.intensityWindow<'T>
let chunkCastToUInt8<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = ChunkFunctions.castToUInt8<'T>
let chunkCastToFloat32<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = ChunkFunctions.castToFloat32<'T>
let chunkCastFromFloat32<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = ChunkFunctions.castFromFloat32<'T>
let chunkCast<'S, 'T when 'S: equality and 'S: (new: unit -> 'S) and 'S: struct and 'S :> System.ValueType
                         and 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> : Stage<Chunk<'S>, Chunk<'T>> =
    if typeof<'S> = typeof<'T> then
        unbox (box (StackCore.identityStage "chunkCast.identity"))
    elif typeof<'T> = typeof<float32> then
        unbox (box (ChunkFunctions.castToFloat32<'S>))
    elif typeof<'T> = typeof<uint8> then
        unbox (box (ChunkFunctions.castToUInt8<'S>))
    elif typeof<'S> = typeof<float32> then
        unbox (box (ChunkFunctions.castFromFloat32<'T>))
    else
        ChunkFunctions.castToFloat32<'S> --> ChunkFunctions.castFromFloat32<'T>
let inline chunkImageAddScalar value = ChunkFunctions.addScalar value
let inline chunkImageSubScalar value = ChunkFunctions.subScalar value
let inline chunkImageMulScalar value = ChunkFunctions.mulScalar value
let inline chunkImageDivScalar value = ChunkFunctions.divScalar value
let inline chunkScalarAddImage value = ChunkFunctions.scalarAdd value
let inline chunkScalarSubImage value = ChunkFunctions.scalarSub value
let inline chunkScalarMulImage value = ChunkFunctions.scalarMul value
let inline chunkScalarDivImage value = ChunkFunctions.scalarDiv value
let inline chunkAddPair<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType and 'T: (static member ( + ) : 'T * 'T -> 'T)> = ChunkFunctions.add<'T>
let inline chunkSubPair<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType and 'T: (static member ( - ) : 'T * 'T -> 'T)> = ChunkFunctions.subtract<'T>
let inline chunkMulPair<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType and 'T: (static member ( * ) : 'T * 'T -> 'T)> = ChunkFunctions.multiply<'T>
let inline chunkDivPair<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType and 'T: (static member ( / ) : 'T * 'T -> 'T)> = ChunkFunctions.divide<'T>
let inline chunkMaxOfPair<'T when 'T: equality and 'T: comparison and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = ChunkFunctions.maximum<'T>
let inline chunkMinOfPair<'T when 'T: equality and 'T: comparison and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = ChunkFunctions.minimum<'T>
let chunkEqual<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = ChunkFunctions.equal<'T>
let chunkNotEqual<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = ChunkFunctions.notEqual<'T>
let chunkGreater<'T when 'T: equality and 'T: comparison and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = ChunkFunctions.greater<'T>
let chunkGreaterEqual<'T when 'T: equality and 'T: comparison and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = ChunkFunctions.greaterEqual<'T>
let chunkLess<'T when 'T: equality and 'T: comparison and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = ChunkFunctions.less<'T>
let chunkLessEqual<'T when 'T: equality and 'T: comparison and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = ChunkFunctions.lessEqual<'T>
let chunkMaskAnd = ChunkFunctions.maskAnd
let chunkMaskOr = ChunkFunctions.maskOr
let chunkMaskXor = ChunkFunctions.maskXor
let chunkMaskNot = ChunkFunctions.maskNot
let convolveNativeXParallelCollect<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = ChunkFunctions.convolveNativeXParallelCollect<'T>
let convolveNativeYParallelCollect<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = ChunkFunctions.convolveNativeYParallelCollect<'T>
let convolveNativeZParallelCollect<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = ChunkFunctions.convolveNativeZParallelCollect<'T>
let finiteDiffKernel1D = ChunkFunctions.finiteDiffKernel1D
let finiteDiffNativeXParallelCollect<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = ChunkFunctions.finiteDiffNativeXParallelCollect<'T>
let finiteDiffNativeYParallelCollect<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = ChunkFunctions.finiteDiffNativeYParallelCollect<'T>
let finiteDiffNativeZParallelCollect<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = ChunkFunctions.finiteDiffNativeZParallelCollect<'T>
let separableConvolveNativeParallelCollect<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = ChunkFunctions.separableConvolveNativeParallelCollect<'T>
let boxFilterNativeParallelCollect<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = ChunkFunctions.boxFilterNativeParallelCollect<'T>
let boxFilterNativeParallelCollectXYZ<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = ChunkFunctions.boxFilterNativeParallelCollectXYZ<'T>
let gaussianFilterNativeParallelCollect<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = ChunkFunctions.gaussianFilterNativeParallelCollect<'T>
let gaussianFilterNativeParallelCollectXYZ<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = ChunkFunctions.gaussianFilterNativeParallelCollectXYZ<'T>
let gradientVectorNativeParallelCollect = ChunkFunctions.gradientVectorNativeParallelCollect
let gradientVectorNativeParallelCollectXYZ = ChunkFunctions.gradientVectorNativeParallelCollectXYZ
let gradientMagnitudeNativeParallelCollect = ChunkFunctions.gradientMagnitudeNativeParallelCollect
let gradientMagnitudeNativeParallelCollectXYZ = ChunkFunctions.gradientMagnitudeNativeParallelCollectXYZ
let hessianUpperNativeParallelCollect = ChunkFunctions.hessianUpperNativeParallelCollect
let hessianUpperNativeParallelCollectXYZ = ChunkFunctions.hessianUpperNativeParallelCollectXYZ
let laplacianNativeParallelCollect = ChunkFunctions.laplacianNativeParallelCollect
let laplacianNativeParallelCollectXYZ = ChunkFunctions.laplacianNativeParallelCollectXYZ
let sobelMagnitudeNativeParallelCollect = ChunkFunctions.sobelMagnitudeNativeParallelCollect
let sobelXNativeParallelCollect<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = ChunkFunctions.sobelXNativeParallelCollect<'T>
let sobelYNativeParallelCollect<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = ChunkFunctions.sobelYNativeParallelCollect<'T>
let sobelZNativeParallelCollect<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = ChunkFunctions.sobelZNativeParallelCollect<'T>
let chunkAddNormalNoise<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = ChunkFunctions.addNormalNoise<'T>
let chunkAddSaltAndPepperNoise<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = ChunkFunctions.addSaltAndPepperNoise<'T>
let chunkAddShotNoise<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = ChunkFunctions.addShotNoise<'T>
let chunkBinaryDilateZonohedral = ChunkFunctions.binaryDilateZonohedral
let chunkBinaryErodeZonohedral = ChunkFunctions.binaryErodeZonohedral
let chunkBinaryOpeningZonohedral = ChunkFunctions.binaryOpeningZonohedral
let chunkBinaryClosingZonohedral = ChunkFunctions.binaryClosingZonohedral
let chunkBinaryWhiteTopHatZonohedral = ChunkFunctions.binaryWhiteTopHatZonohedral
let chunkBinaryWhiteTopHatZonohedralParallel = ChunkFunctions.binaryWhiteTopHatZonohedralParallel
let chunkBinaryBlackTopHatZonohedral = ChunkFunctions.binaryBlackTopHatZonohedral
let chunkBinaryBlackTopHatZonohedralParallel = ChunkFunctions.binaryBlackTopHatZonohedralParallel
let chunkBinaryGradientZonohedral = ChunkFunctions.binaryGradientZonohedral
let chunkBinaryGradientZonohedralParallel = ChunkFunctions.binaryGradientZonohedralParallel
let chunkBinaryContourZonohedral = ChunkFunctions.binaryContourZonohedral
let chunkBinaryContourZonohedralParallel = ChunkFunctions.binaryContourZonohedralParallel
let readZarrSlabStacked<'T when 'T: equality> = StackIO.readZarrSlabStacked<'T>
let readZarrSlab<'T when 'T: equality> = StackIO.readZarrSlab<'T>
let readZarrRandom<'T when 'T: equality> = StackIO.readZarrRandom<'T>
let readZarrRange<'T when 'T: equality> = StackIO.readZarrRange<'T>
let readNexusSlabStacked<'T when 'T: equality> = StackIO.readNexusSlabStacked<'T>
let readNexusSlab<'T when 'T: equality> = StackIO.readNexusSlab<'T>
let readNexusRandom<'T when 'T: equality> = StackIO.readNexusRandom<'T>
let readNexusRange<'T when 'T: equality> = StackIO.readNexusRange<'T>
let readPointSet = StackPoints.readPointSet
let coordinateX<'T when 'T: equality> width height depth = StackImageFunctions.coordinateX<'T> width height depth
let coordinateY<'T when 'T: equality> width height depth = StackImageFunctions.coordinateY<'T> width height depth
let coordinateZ<'T when 'T: equality> width height depth = StackImageFunctions.coordinateZ<'T> width height depth
let imageCenter = TinyLinAlg.imageCenter
let randomRigidTransformAround = TinyLinAlg.randomRigidTransformAround
let randomRigidTransform = TinyLinAlg.randomRigidTransform
let deleteIfExists = StackIO.deleteIfExists
let write = StackIO.write
let writeThrough = StackIO.write
let writeChunkSlices<'T when 'T: equality> = StackIO.writeChunkSlices<'T>
let writeColorChunkSlices = StackIO.writeColorChunkSlices
let writeVolume<'T when 'T: equality> = StackIO.writeVolume<'T>
let writeZarrWithCompression = StackIO.writeZarrWithCompression
let writeZarr = StackIO.writeZarr
let writeZarrComplex64InterleavedFloat32 = StackIO.writeZarrComplex64InterleavedFloat32
let fftZComplex64InterleavedZarrTiles = StackIO.fftZComplex64InterleavedZarrTiles
let writeZarrSlabWithCompression = StackIO.writeZarrSlabWithCompression
let writeZarrSlabNamedWithCompression = StackIO.writeZarrSlabNamedWithCompression
let writeZarrSlab = StackIO.writeZarrSlab
let writeZarrSlabNamed = StackIO.writeZarrSlabNamed
let writeNexus = StackIO.writeNexus
let writeNexusSlab = StackIO.writeNexusSlab
let writeChunks = StackIO.writeChunks
let writePointSet = StackPoints.writePointSet
let writeCSVPointSet = StackPoints.writeCSVPointSet
let vectorizeMatrix = StackPoints.vectorizeMatrix
let unvectorizeMatrix = StackPoints.unvectorizeMatrix
let pointPairDistances = StackPoints.pointPairDistances
let writeMatrix = StackPoints.writeMatrix
let writeCSVMatrix = StackPoints.writeCSVMatrix
let writeCSVHistogram<'T when 'T: comparison> = StackPoints.writeCSVHistogram<'T>
let selectGroupedValueOutput = StackPoints.selectGroupedValueOutput
let writeMesh = StackMesh.writeMesh
let meshFilePath = StackMesh.meshFilePath

// //////////////////// StackRegistration
let defaultAffineRegistrationOptions = StackRegistration.defaultAffineRegistrationOptions
let earthMoversDistance = StackRegistration.earthMoversDistance
let transformPointSet = StackRegistration.transformPointSet
let inverseAffine = StackRegistration.inverseAffine
let affineToMatrix = StackRegistration.affineToMatrix
let matrixToAffine = StackRegistration.matrixToAffine
let affineRegistration = StackRegistration.affineRegistration
let affineRegistrationMatrices = StackRegistration.affineRegistrationMatrices
let ransacFit = StackRansac.fit
let affine2DFromMatches = StackRansac.affine2DFromMatches
let affine2DRansac = StackRansac.affine2DRansac

// //////////////////// StackManifest
let identityImageSetTransform = StackManifest.identityTransform
let imageSetTransformFromMatrix = StackManifest.transformFromMatrix
let imageSetTransformToMatrix = StackManifest.transformToMatrix
let imageSetTransformFromAffine = StackManifest.transformFromAffine
let imageSetTransformToAffine = StackManifest.transformToAffine
let createImageSetManifest = StackManifest.createManifest
let identityImageSetManifest = StackManifest.identityManifest
let imageSetGrid = StackManifest.imageSetGrid
let withImageSetGrid = StackManifest.withGrid
let imageSetGridIndexTransform = StackManifest.gridIndexTransform
let composeImageSetTransforms = StackManifest.composeTransforms
let updateMovingImageSetItemTransformFromRegistration = StackManifest.updateMovingItemTransformFromRegistration
let imageSetItem = StackManifest.spatialDataItem
let scalarImageSetItem = StackManifest.scalarImageItem
let gridImageSetItem = StackManifest.gridImageItem
let vectorImageSetItem = StackManifest.vectorImageItem
let pointSetManifestItem = StackManifest.pointSetItem
let triangleMeshManifestItem = StackManifest.triangleMeshItem
let matrixManifestItem = StackManifest.matrixItem
let imageSetMember = StackManifest.imageMember
let addImageSetItem = StackManifest.addItem
let addImageSetMember = StackManifest.addImage
let replaceImageSetItemTransform = StackManifest.replaceItemTransform
let replaceImageSetMemberTransform = StackManifest.replaceImageTransform
let writeImageSetManifest = StackManifest.writeManifest
let readImageSetManifest = StackManifest.readManifest

// //////////////////// StackStitching
let createStitchPlan = StackStitching.createStitchPlan
let stitchManifestImages<'T when 'T: equality> = StackStitching.stitchManifestImages<'T>

// //////////////////// StackObjects
let streamConnectedObjects<'T when 'T: equality> = StackObjects.streamConnectedObjects<'T>
let streamConnectedObjectsChunk<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = StackObjects.streamConnectedObjectsChunk<'T>
let removeSmallObjects = StackObjects.removeSmallObjects
let fillSmallHoles = StackObjects.fillSmallHoles
let paintObjects = StackObjects.paintObjects
let paintObjectsCropped = StackObjects.paintObjectsCropped
let paintObjectsChunk = StackObjects.paintObjectsChunk
let paintObjectsCroppedChunk = StackObjects.paintObjectsCroppedChunk
let measureObjects = StackObjects.measureObjects
let objectSizes = StackObjects.objectSizes
let objectSizeStats = StackObjects.objectSizeStats
let histogram = StackObjects.histogram
let chunkRemoveSmallObjects = StackObjects.removeSmallObjectsChunk
let chunkFillSmallHoles = StackObjects.fillSmallHolesChunk

// //////////////////// StackAffineResampler
let resampleAffineFromChunks = StackAffineResampler.resampleAffineFromChunks
let resampleAffineChunk<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = StackAffineResampler.resampleAffineChunk<'T>
let resampleAffine = StackAffineResampler.resampleAffine

// //////////////////// StackImageFunctions
type ImageStats = ImageFunctions.ImageStats

let cast<'S,'T when 'S: equality and 'T: equality> = StackImageFunctions.cast<'S,'T>
let add = StackImageFunctions.add
let addPair = StackImageFunctions.addPair
let inline scalarAddImage<^T when ^T: equality and ^T: (static member op_Explicit: ^T -> float)> = StackImageFunctions.scalarAddImage<^T>
let inline imageAddScalar<^T when ^T: equality and ^T: (static member op_Explicit: ^T -> float)> = StackImageFunctions.imageAddScalar<^T>
let sub = StackImageFunctions.sub
let subPair = StackImageFunctions.subPair
let inline scalarSubImage<^T when ^T: equality and ^T: (static member op_Explicit: ^T -> float)> = StackImageFunctions.scalarSubImage<^T>
let inline imageSubScalar<^T when ^T: equality and ^T: (static member op_Explicit: ^T -> float)> = StackImageFunctions.imageSubScalar<^T>
let mul = StackImageFunctions.mul
let mulPair = StackImageFunctions.mulPair
let inline scalarMulImage<^T when ^T: equality and ^T: (static member op_Explicit: ^T -> float)> = StackImageFunctions.scalarMulImage<^T>
let inline imageMulScalar<^T when ^T: equality and ^T: (static member op_Explicit: ^T -> float)> = StackImageFunctions.imageMulScalar<^T>
let div = StackImageFunctions.div
let divPair = StackImageFunctions.divPair
let inline scalarDivImage<^T when ^T: equality and ^T: (static member op_Explicit: ^T -> float)> = StackImageFunctions.scalarDivImage<^T>
let inline imageDivScalar<^T when ^T: equality and ^T: (static member op_Explicit: ^T -> float)> = StackImageFunctions.imageDivScalar<^T>
let maxOfPair = StackImageFunctions.maxOfPair
let minOfPair = StackImageFunctions.minOfPair
let getMinMax = StackImageFunctions.getMinMax
let failTypeMismatch<'T> = StackCore.failTypeMismatch<'T>
let toVectorImage<'T when 'T: equality> : Stage<Image<'T> * Image<'T>, Image<'T list>> = StackImageFunctions.toVectorImage<'T>
let vectorElement<'T when 'T: equality> componentId : Stage<Image<'T list>, Image<'T>> = StackImageFunctions.vectorElement<'T> componentId
let vectorRange<'T when 'T: equality> firstComponent componentCount : Stage<Image<'T list>, Image<'T list>> = StackImageFunctions.vectorRange<'T> firstComponent componentCount
let vector3ToColor inputMinimum inputMaximum : Stage<Image<float list>, Image<uint8 list>> = StackImageFunctions.vector3ToColor inputMinimum inputMaximum
let colorToVector3 outputMinimum outputMaximum : Stage<Image<uint8 list>, Image<float list>> = StackImageFunctions.colorToVector3 outputMinimum outputMaximum
let appendVectorElement : Stage<Image<float list> * Image<float>, Image<float list>> = StackImageFunctions.appendVectorElement
let vectorMapElements functionName : Stage<Image<float list>, Image<float list>> = StackImageFunctions.vectorMapElements functionName
let vectorDot : Stage<Image<float list> * Image<float list>, Image<float>> = StackImageFunctions.vectorDot
let vectorCross3D : Stage<Image<float list> * Image<float list>, Image<float list>> = StackImageFunctions.vectorCross3D
let vectorAngleTo reference : Stage<Image<float list>, Image<float>> = StackImageFunctions.vectorAngleTo reference
let Re : Stage<Image<System.Numerics.Complex>, Image<float>> = StackImageFunctions.Re
let Im : Stage<Image<System.Numerics.Complex>, Image<float>> = StackImageFunctions.Im
let modulus : Stage<Image<System.Numerics.Complex>, Image<float>> = StackImageFunctions.modulus
let arg : Stage<Image<System.Numerics.Complex>, Image<float>> = StackImageFunctions.arg
let conjugate : Stage<Image<System.Numerics.Complex>, Image<System.Numerics.Complex>> = StackImageFunctions.conjugate
let toComplex : Stage<Image<float> * Image<float>, Image<System.Numerics.Complex>> = StackImageFunctions.toComplex
let polarToComplex : Stage<Image<float> * Image<float>, Image<System.Numerics.Complex>> = StackImageFunctions.polarToComplex
let FFT<'T when 'T: equality> chunkX chunkY chunkZ : Stage<Image<'T>, Image<System.Numerics.Complex>> = StackImageFunctions.FFT<'T> chunkX chunkY chunkZ
let FFTFloat32<'T when 'T: equality> chunkX chunkY chunkZ : Stage<Image<'T>, Image<Image.ComplexFloat32>> = StackImageFunctions.FFTFloat32<'T> chunkX chunkY chunkZ
let invFFT chunkX chunkY chunkZ : Stage<Image<System.Numerics.Complex>, Image<float>> = StackImageFunctions.invFFT chunkX chunkY chunkZ
let invFFTFloat32 chunkX chunkY chunkZ : Stage<Image<Image.ComplexFloat32>, Image<float32>> = StackImageFunctions.invFFTFloat32 chunkX chunkY chunkZ
let shiftFFT chunkX chunkY chunkZ : Stage<Image<System.Numerics.Complex>, Image<System.Numerics.Complex>> = StackImageFunctions.shiftFFT chunkX chunkY chunkZ
let abs<'T when 'T: equality>= StackImageFunctions.abs<'T>
let acos<'T when 'T: equality>= StackImageFunctions.acos<'T>
let asin<'T when 'T: equality>= StackImageFunctions.asin<'T>
let atan<'T when 'T: equality>= StackImageFunctions.atan<'T>
let cos<'T when 'T: equality>= StackImageFunctions.cos<'T>
let sin<'T when 'T: equality>= StackImageFunctions.sin<'T>
let tan<'T when 'T: equality>= StackImageFunctions.tan<'T>
let exp<'T when 'T: equality>= StackImageFunctions.exp<'T>
let log10<'T when 'T: equality>= StackImageFunctions.log10<'T>
let log<'T when 'T: equality>= StackImageFunctions.log<'T>
let round<'T when 'T: equality>= StackImageFunctions.round<'T>
let sqrt<'T when 'T: equality>= StackImageFunctions.sqrt<'T>
let sqrtWindowed<'T when 'T: equality> = StackImageFunctions.sqrtWindowed<'T>
let square<'T when 'T: equality>= StackImageFunctions.square<'T>
let clamp<'T when 'T: equality> lower upper : Stage<Image<'T>, Image<'T>> = StackImageFunctions.clamp<'T> lower upper
let shiftScale<'T when 'T: equality> shift scale : Stage<Image<'T>, Image<'T>> = StackImageFunctions.shiftScale<'T> shift scale
let intensityStretch<'T when 'T: equality> inputMinimum inputMaximum outputMinimum outputMaximum : Stage<Image<'T>, Image<'T>> = StackImageFunctions.intensityStretch<'T> inputMinimum inputMaximum outputMinimum outputMaximum
let smoothWMedian<'T when 'T: equality> radius winSz : Stage<Image<'T>, Image<'T>> = StackImageFunctions.smoothWMedian<'T> radius winSz
let smoothWBilateral<'T when 'T: equality> domainSigma rangeSigma winSz : Stage<Image<'T>, Image<'T>> = StackImageFunctions.smoothWBilateral<'T> domainSigma rangeSigma winSz
let gradientMagnitude<'T when 'T: equality> winSz : Stage<Image<'T>, Image<'T>> = StackImageFunctions.gradientMagnitude<'T> winSz
let gradient order winSz : Stage<Image<float>, Image<float list>> = StackImageFunctions.gradient order winSz
let sobelEdge<'T when 'T: equality> winSz : Stage<Image<'T>, Image<'T>> = StackImageFunctions.sobelEdge<'T> winSz
let laplacian<'T when 'T: equality> winSz : Stage<Image<'T>, Image<'T>> = StackImageFunctions.laplacian<'T> winSz
let grayscaleErode<'T when 'T: equality> radius winSz : Stage<Image<'T>, Image<'T>> = StackImageFunctions.grayscaleErode<'T> radius winSz
let grayscaleDilate<'T when 'T: equality> radius winSz : Stage<Image<'T>, Image<'T>> = StackImageFunctions.grayscaleDilate<'T> radius winSz
let grayscaleOpening<'T when 'T: equality> radius winSz : Stage<Image<'T>, Image<'T>> = StackImageFunctions.grayscaleOpening<'T> radius winSz
let grayscaleClosing<'T when 'T: equality> radius winSz : Stage<Image<'T>, Image<'T>> = StackImageFunctions.grayscaleClosing<'T> radius winSz
let whiteTopHat<'T when 'T: equality> radius winSz : Stage<Image<'T>, Image<'T>> = StackImageFunctions.whiteTopHat<'T> radius winSz
let blackTopHat<'T when 'T: equality> radius winSz : Stage<Image<'T>, Image<'T>> = StackImageFunctions.blackTopHat<'T> radius winSz
let morphologicalGradient<'T when 'T: equality> radius winSz : Stage<Image<'T>, Image<'T>> = StackImageFunctions.morphologicalGradient<'T> radius winSz
let binaryContour = StackImageFunctions.binaryContour
let binaryMedian = StackImageFunctions.binaryMedian
let equal<'T when 'T: equality> = StackImageFunctions.equal<'T>
let notEqual<'T when 'T: equality> = StackImageFunctions.notEqual<'T>
let greater<'T when 'T: equality> = StackImageFunctions.greater<'T>
let greaterEqual<'T when 'T: equality> = StackImageFunctions.greaterEqual<'T>
let less<'T when 'T: equality> = StackImageFunctions.less<'T>
let lessEqual<'T when 'T: equality> = StackImageFunctions.lessEqual<'T>
let maskAnd = StackImageFunctions.maskAnd
let maskOr = StackImageFunctions.maskOr
let maskXor = StackImageFunctions.maskXor
let maskNot = StackImageFunctions.maskNot
let labelContour<'T when 'T: equality> fullyConnected winSz : Stage<Image<'T>, Image<'T>> = StackImageFunctions.labelContour<'T> fullyConnected winSz
let changeLabel<'T when 'T: equality> fromLabel toLabel : Stage<Image<'T>, Image<'T>> = StackImageFunctions.changeLabel<'T> fromLabel toLabel
let marchingCubes<'T when 'T: equality> = StackMesh.marchingCubes<'T>
let marchingCubesChunk<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = StackMesh.marchingCubesChunk<'T>
let surfaceArea = StackMesh.surfaceArea
let dogKeypoints<'T when 'T: equality> = StackPoints.dogKeypoints<'T>
let logBlobKeypoints<'T when 'T: equality> = StackPoints.logBlobKeypoints<'T>
let hessianKeypoints<'T when 'T: equality> = StackPoints.hessianKeypoints<'T>
let harris3DKeypoints<'T when 'T: equality> = StackPoints.harris3DKeypoints<'T>
let forstner3DKeypoints<'T when 'T: equality> = StackPoints.forstner3DKeypoints<'T>
let phaseCongruencyKeypoints<'T when 'T: equality> = StackPoints.phaseCongruencyKeypoints<'T>
let siftKeypoints<'T when 'T: equality> = StackPoints.siftKeypoints<'T>
let chunkDogKeypoints<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = StackPoints.dogKeypointsChunk<'T>
let chunkLogBlobKeypoints<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = StackPoints.logBlobKeypointsChunk<'T>
let chunkHessianKeypoints<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = StackPoints.hessianKeypointsChunk<'T>
let chunkHarris3DKeypoints<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = StackPoints.harris3DKeypointsChunk<'T>
let chunkForstner3DKeypoints<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = StackPoints.forstner3DKeypointsChunk<'T>
let chunkPhaseCongruencyKeypoints<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = StackPoints.phaseCongruencyKeypointsChunk<'T>
let chunkSiftKeypoints<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = StackPoints.siftKeypointsChunk<'T>
let resize<'T when 'T: equality> = StackImageFunctions.resize<'T>
let resample<'T when 'T: equality> = StackImageFunctions.resample<'T>
let imHistogram = StackImageFunctions.imHistogram
let imHistogramFixedBins = StackImageFunctions.imHistogramFixedBins
let histogramEstimate<'T when 'T: equality and 'T: comparison> = StackImageFunctions.histogramEstimate<'T>
let estimateHistogram<'T when 'T: equality and 'T: comparison> = StackImageFunctions.estimateHistogram<'T>
let histogramEstimateMap<'T when 'T: comparison> = StackImageFunctions.histogramEstimateMap<'T>
let histogramEqualization histogram = StackImageFunctions.histogramEqualization histogram
let sumProjection<'T when 'T: equality> = StackImageFunctions.sumProjection<'T>
let volume = StackImageFunctions.volume
let fitBiasModel<'T when 'T: equality> = StackBias.fitBiasModel<'T>
let fitBiasModelMasked<'T when 'T: equality> = StackBias.fitBiasModelMasked<'T>
let fitBiasModelChunk<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = StackBias.fitBiasModelChunk<'T>
let fitBiasModelChunkMasked<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = StackBias.fitBiasModelChunkMasked<'T>
let correctBias<'T when 'T: equality> = StackBias.correctBias<'T>
let correctBiasMasked<'T when 'T: equality> = StackBias.correctBiasMasked<'T>
let correctBiasChunk<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = StackBias.correctBiasChunk<'T>
let correctBiasChunkMasked<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = StackBias.correctBiasChunkMasked<'T>
let chunkSerialPolynomialBiasCorrect<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = StackBias.serialPolynomialBiasCorrectChunk<'T>
let serialIdentityManifest = StackSerialSections.serialIdentityManifest
let serialPolynomialBiasCorrect<'T when 'T: equality> = StackSerialSections.serialPolynomialBiasCorrect<'T>
let serialEstTrans<'T when 'T: equality> = StackSerialSections.serialEstTrans<'T>
let serialEstBoundingBox<'T when 'T: equality> = StackSerialSections.serialEstBoundingBox<'T>
let serialApplyTrans<'T when 'T: equality> = StackSerialSections.serialApplyTrans<'T>
let serialTransImage<'T when 'T: equality> = StackSerialSections.serialTransImage<'T>
let serialTransManifest<'T when 'T: equality> = StackSerialSections.serialTransManifest<'T>
let serialApplyManifestInBoundingBox<'T when 'T: equality> = StackSerialSections.serialApplyManifestInBoundingBox<'T>
let chunkSerialEstTrans<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = StackSerialSections.serialEstTransChunk<'T>
let chunkSerialEstBoundingBox<'T when 'T: equality> = StackSerialSections.serialEstBoundingBoxChunk<'T>
let chunkSerialApplyTrans<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = StackSerialSections.serialApplyTransChunk<'T>
let chunkSerialTransChunk<'T when 'T: equality> = StackSerialSections.serialTransChunk<'T>
let chunkSerialTransManifest<'T when 'T: equality> = StackSerialSections.serialTransManifestChunk<'T>
let chunkSerialApplyManifestInBoundingBox<'T when 'T: equality and 'T: (new: unit -> 'T) and 'T: struct and 'T :> System.ValueType> = StackSerialSections.serialApplyManifestInBoundingBoxChunk<'T>
let quantiles = StackImageFunctions.quantiles
let otsuThresholdFromHistogram = StackImageFunctions.otsuThresholdFromHistogram
let momentsThresholdFromHistogram = StackImageFunctions.momentsThresholdFromHistogram
let histogramCounts<'T when 'T: comparison> = StackImageFunctions.histogramCounts<'T>
let inline histogram2pairs< ^T when ^T: comparison and ^T: (static member op_Explicit: ^T -> float) > = StackImageFunctions.histogram2pairs<'T>
let inline map2pairs< ^T, ^S when ^T: comparison and ^T: (static member op_Explicit: ^T -> float) and  ^S: (static member op_Explicit: ^S -> float) > = StackImageFunctions.map2pairs<'T,'S>
let inline pairs2floats< ^T, ^S when ^T: (static member op_Explicit: ^T -> float) and  ^S: (static member op_Explicit: ^S -> float) > = StackImageFunctions.pairs2floats<'T,'S>
let inline pairs2ints< ^T, ^S when ^T: (static member op_Explicit: ^T -> int) and  ^S: (static member op_Explicit: ^S -> int) > = StackImageFunctions.pairs2ints<'T,'S>
let computeStats = StackImageFunctions.computeStats
let smoothWGauss = StackImageFunctions.smoothWGauss
let createPadding<'T when 'T: equality> = StackImageFunctions.createPadding<'T>
let crop<'T when 'T: equality> = StackImageFunctions.crop<'T>
let convolve = StackImageFunctions.convolve
let conv = StackImageFunctions.conv
let finiteDiff = StackImageFunctions.finiteDiff
let structureTensor sigma rho : Stage<Image<float>, Image<float list>> = StackImageFunctions.structureTensor sigma rho
let PCA components : Stage<Image<float list>, Image<float list>> = StackImageFunctions.PCA components
let selectGroupedOutput groupSize part : Stage<Image<'T>, Image<'T>> = StackImageFunctions.selectGroupedOutput groupSize part
let identity<'T> : Stage<'T, 'T> = StackCore.identityStage "identity"
let erode = StackImageFunctions.erode
let dilate = StackImageFunctions.dilate
let dilateZonohedral = StackImageFunctions.dilateZonohedral
let erodeZonohedral = StackImageFunctions.erodeZonohedral
let opening = StackImageFunctions.opening
let openingZonohedral = StackImageFunctions.openingZonohedral
let closing = StackImageFunctions.closing
let closingZonohedral = StackImageFunctions.closingZonohedral
let connectedComponents = StackImageFunctions.connectedComponents
let connectedComponentsLabels = StackImageFunctions.connectedComponentsLabels
let connectedComponentsFullVolumeMemoryBytes = StackImageFunctions.connectedComponentsFullVolumeMemoryBytes
let connectedComponentsFullVolumeFits = StackImageFunctions.connectedComponentsFullVolumeFits
let relabelComponents = StackImageFunctions.relabelComponents
let signedDistanceBand = StackImageFunctions.signedDistanceBand
let threshold = StackImageFunctions.threshold
let windowSkipTakeM outputStart outputCount = StackCore.windowSkipTakeM outputStart outputCount
let addNormalNoise = StackImageFunctions.addNormalNoise
let addSaltAndPepperNoise = StackImageFunctions.addSaltAndPepperNoise
let addShotNoise = StackImageFunctions.addShotNoise
let addSpeckleNoise = StackImageFunctions.addSpeckleNoise
let show = StackImageFunctions.show
let plot = StackImageFunctions.plot
let print = StackImageFunctions.print
let zero<'T when 'T: equality>= StackImageFunctions.zero<'T>
let polygonMask = StackImageFunctions.polygonMask
let repeat<'T when 'T: equality> = StackImageFunctions.repeat<'T>
let repeatStage<'T when 'T: equality> = StackImageFunctions.repeatStage<'T>
let euler2DTransformPath = StackImageFunctions.euler2DTransformPath
let createByEuler2DTransformFromImage<'T when 'T: equality> = StackImageFunctions.createByEuler2DTransformFromImage<'T>
let normalNoise<'T when 'T: equality> = StackImageFunctions.normalNoise<'T>
let saltAndPepperNoise<'T when 'T: equality> = StackImageFunctions.saltAndPepperNoise<'T>
let shotNoise<'T when 'T: equality> = StackImageFunctions.shotNoise<'T>
let speckleNoise<'T when 'T: equality> = StackImageFunctions.speckleNoise<'T>
let createByEuler2DTransform<'T when 'T: equality>= StackImageFunctions.createByEuler2DTransform<'T>
let empty = StackImageFunctions.empty
type ComponentStatistics = StackImageFunctions.ComponentStatistics
type ConnectedComponentTranslationTable = StackImageFunctions.ConnectedComponentTranslationTable
let makeConnectedComponentTranslationTable = StackImageFunctions.makeConnectedComponentTranslationTable
let makeConnectedComponentLabelTranslationTable = StackImageFunctions.makeConnectedComponentLabelTranslationTable
let updateConnectedComponents = StackImageFunctions.updateConnectedComponents
let permuteAxes = StackImageFunctions.permuteAxes
